= Collections

== Set

=== EnumSet

* specialized Set collection to work with enum classes
* Enum sets are represented internally as *bit vectors*

==== RegularEnumSet

RegularEnumSet uses a *single long to represent the bit vector*. Each bit of the long element represents a value of the enum. The i-th value of the enum will be stored in the i-th bit, so it’s quite easy to know whether a value is present or not. Since long is a 64-bit data type, this implementation can store up to 64 elements.

==== JumboEnumSet

JumboEnumSet uses an array of long elements as a bit vector. This lets this implementation store more than 64 elements.

* works like the RegularEnumSet but making some extra calculations to find the array index where the value is stored.

* the first long element of the array will store the 64 first values of the enum
* the second element the next 64, and so on.

=== HashSet

* backed by a *hash table* (actually a HashMap instance).
* no guarantees as to the iteration order of the set; in particular, it does not guarantee that the order will remain constant over time.
* permits the null element.

=== LinkedHashSet

* predictable iteration order.
* maintains a doubly-linked list running through all of its entries.
* defines the iteration ordering, which is the order in which elements were inserted into the set (insertion-order).

NOTE: that insertion order is not affected if an element is re-inserted into the set.

=== CopyOnWriteArraySet

* A Set that uses an internal *CopyOnWriteArrayList* for all of its operations.

* It is thread-safe.

* It is best suited for applications in which set *sizes generally stay small*, read-only operations vastly outnumber mutative operations, and you need to prevent interference among threads during traversal.

* Mutative operations (add, set, remove, etc.) are expensive since they usually entail copying the entire underlying array.
* Iterators do not support the mutative remove operation.

* Traversal via iterators is fast and cannot encounter interference from other threads.
* Iterators rely on unchanging snapshots of the array at the time the iterators were constructed. Additional operations are provided to take advantage of the ordering.
* All elements inserted into a sorted set must implement the Comparable interface

=== SortedSet

A sorted set allows iteration of its entries in ascending order.

=== NavigableSet

A SortedSet extended with navigation methods reporting closest matches for given search targets.

* Methods lower(), floor(), ceiling(), and higher() return elements respectively less than, less than or equal, greater than or equal, and greater than a given element, returning null if there is no such element.

=== TreeSet

* The iterators returned by this class's *iterator method are fail-fast*.
* TreeSet uses a *self-balancing binary search tree* (RedBlack tree) as the backing data-structure.
* It's *not thread safe* and stores keys in ascending order rather than in their insertion order.

* The elements are ordered using their natural ordering, or by a Comparator provided at set creation time.
* This implementation provides guaranteed *log(n) time cost for add, remove and contains operations*.

=== ConcurrentSkipListSet

* Skiplist is a data structure used for *fast search*.
* It stores sorted list of items, very much like a binary search tree. It consists of a base list holding the elements, together with a tower of lists maintaining a linked hierarchy of subsequences, each skipping over fewer elements.
* Create multiple layers so that we can skip some nodes. Iterators are weakly consistent, returning elements reflecting the state of the set at some point at or since the creation of the iterator.

== Queues

=== ArrayDeque

* a double-ended queue that supports addition or removal of elements from either end of the data structure.
* can be used as a *queue* (first-in-first-out/FIFO) or as a *stack* (last-in-first-out/LIFO).
* Array deques have no capacity restrictions; they grow as necessary to support usage.

=== PriorityQueue

* are based on the heap data-structure.
* The elements of the priority queue are *ordered according to their natural ordering*, or by a Comparator provided at queue construction time.
* The queue can be made to behave like a max heap using the passed in comparator.
* The head of this queue is the least element with respect to the specified ordering. If multiple elements are tied for least value, the head is one of those elements and ties are broken arbitrarily.

=== ConcurrentLinkedQueue

An unbounded thread-safe queue based on linked nodes. This queue orders elements FIFO

=== BlockingQueue

IMPORTANT: A blocking queue is a queue that blocks when you try to dequeue from it and the queue is empty, or if you try to enqueue items to it and the queue is already full.

* are designed to be used primarily for producer-consumer queues. BlockingQueue implementations are thread-safe.
* All queuing methods achieve their effects atomically using internal locks or other forms of concurrency control.
* the bulk Collection operations addAll, containsAll, retainAll and removeAll are not necessarily performed atomically unless specified otherwise in an implementation.

=== PriorityBlockingQueue

PriorityBlockingQueue defines an ordering on its elements in the same manner as a priority heap and additionally exposes blocking insert and retrieval operations on the queue.

* It implements the BlockingQueue interface.

=== LinkedBlockingQueue

A blocking queue based on linked nodes. New elements are added at the tail.

=== ArrayBlockingQueue

A array based blocking queue.

* This is a classic bounded buffer, in which a fixed-sized array holds elements inserted by producers and extracted by consumers.

=== DelayQueue

A delay queue is a blocking queue but when a consumer wants to take an element off of the queue, it is only allowed to do so when the delay for that particular element has expired.

=== SynchronousQueue

* has two supported operations: take() and put(), and both of them are blocking.
* For instance, when we want to add an element to the queue, we need to call the put() method. That method will block until some other thread calls the take() method, signaling that it is ready to take an element.

IMPORTANT: Although the SynchronousQueue has an interface of a queue, we should think about it as an exchange point for a single element between two threads, in which one thread is handing off an element, and another thread is taking that element.

=== BlockingDeque

It is a Deque that additionally supports blocking operations that wait for the deque to become non-empty when retrieving an element, and wait for space to become available in the deque when storing an element.


== List

=== ArrayList

* This is a unsynchronized resizable array based implementation of the List interface.
* As elements are added to an ArrayList, its capacity grows automatically.
* Iterators returned for this class are fail fast.

=== LinkedList

* This is a unsynchronized doubly-linked list implementation of the Deque and List interfaces.
* Returned iterators for this list are fail fast.

=== CopyOnWriteArrayList

* This is a thread-safe variant of the ArrayList.
* Any write operations trigger a fresh copy of the underling array to be created.

== Map

=== HashMap

* Unsynchronized hash table based implementation of the Map interface.
* This class makes no guarantees as to the order of the map

=== LinkedHashMap

* Hash table and linked list implementation of the Map interface, with *predictable iteration order*.
* maintains a doubly-linked list running through all of its entries.
* This linked list defines the iteration ordering, which is normally the order in which keys were inserted into the map

=== WeakHashMap

* an implementation of the Map interface.
* WeakHashMap is almost same as HashMap except in case of WeakHashMap, if object is specified as key doesn't contain any references- it is eligible for garbage collection even though it is associated with WeakHashMap.

=== IdentityHashMap

* This class implements the Map interface with a hash table, using reference-equality in place of object-equality when comparing keys (and values).
* In other words, in an IdentityHashMap, two keys k1 and k2 are considered equal if and only if (k1==k2)
* designed for use only in the rare cases wherein reference-equality semantics are required.
* Iterators returned for this class are failfast.

=== EnumMap

* A specialized unsynchronized Map implementation for use with enum type keys.
* All of the keys in an enum map must come from a single enum type that is specified, explicitly or implicitly, when the map is created.
* Enum maps are represented internally as arrays. This representation is extremely compact and efficient.
* Iterators returned for this class are weakly consistent i.e. they may or may not show the effects of any modifications to the map that occur while the iteration is in progress.
* Keys appear in the map in the order in which the enum constants are declared.

=== SortedMap

* A Map that further provides a total ordering on its keys.
* The map is ordered according to the natural ordering of its keys, or by a Comparator typically provided at sorted map creation time.
* All keys inserted into a sorted map must implement the Comparable interface.

=== NaigableMap

* A SortedMap extended with navigation methods returning the closest matches for given search targets.
* Methods lowerEntry, floorEntry, ceilingEntry, and higherEntry return Map.Entry objects associated with keys respectively less than, less than or equal, greater than or equal, and greater than a given key, returning null if there is no such key.
* A NavigableMap may be accessed and traversed in either ascending or descending key order.

=== TreeMap

* A Red-Black tree based unsynchronized NavigableMap implementation.
* This implementation provides guaranteed log(n) time cost for the containsKey, get, put and remove operations.
* The map is sorted according to the natural ordering of its keys, or by a Comparator provided at map creation time, depending on which constructor is used.

=== ConcurrentHashMap

* A hash table supporting full concurrency of retrievals and high expected concurrency for updates.
* This class obeys the same functional specification as Hashtable, and includes versions of methods corresponding to each method of Hashtable.
* However, even though all operations are thread-safe, retrieval operations do not entail locking, and there is not any support for locking the entire table in a way that prevents all access.
* This class is fully interoperable with Hashtable in programs that rely on its thread safety but not on its synchronization details.

=== ConcurrentNavigableMap

A ConcurrentMap supporting NavigableMap operations, and recursively so for its navigable sub-maps.

=== ConcurrentSkipListMap

A ConcurrentSkipListMap stores the Map in the natural order of its keys (or some other key order you define). So it'll have slower get/put/contains operations than a HashMap, but to offset this it supports the SortedMap and NavigableMap interfaces.








