= Docker

== Images
An image is a file that represents a packaged application with all the dependencies needed to run correctly. In other words, we could say that a Docker image is like a Java class.

Images are built as a series of layers. Layers are assembled on top of one another.

----
$ docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
postgres             11.6                d3d96b1e5d48        4 weeks ago         332MB
----

== Containers
A container is an instance of an image. Each container can be identified by its ID. Going back to our Java development analogy, we could say that a container is like an instance of a class.

Docker defines seven states for a container: created, restarting, running, removing, paused, exited, and dead.

One big advantage is that containers are like lightweight VMs. Their behaviors are completely isolated from each other. This means that we can run multiple containers of the same image, having each one in a different state with different data and different IDs.

=== Containers Lifecycle
Starting up a new container requires us to create it and then start it.
----
docker container create <image_name>:<tag>
docker container start <container_id>
----
OR
----
docker run <image_name>:<tag>
----
Pause:
----
docker pause <container_id>
docker unpause <container_id>
----

Stop a running container and then rerun it:
----
docker stop <container_id>
docker start <container_id>
----
Remove a container:
----
docker container rm <container_id>
----
*Only containers in the stopped or created state can be removed.*



== Volumes
Remove volumes if no space left on device
Cleanup:

$ docker volume rm $(docker volume ls -qf dangling=true)
Additional commands:

List dangling volumes:

$ docker volume ls -qf dangling=true
List all volumes:

$ docker volume ls

docker system prune
This will remove:

- all stopped containers
- all volumes not used by at least one container
- all networks not used by at least one container
- all dangling images
As below, this is nuclear.

To clean your system, first remove containers

$ docker rm $(docker ps -aq)
then remove images

$ docker rmi $(docker images -q)

== Accessing a container
=== Connecting to an Existing Container

----
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                NAMES
b7a9f5eb6b85        rabbitmq:3          "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   trusting_bose
----

Connecting:
----
$ docker exec -it b7a9f5eb6b85 sh
----
* docker exec tells Docker that we want to execute a command into a running container
* The -it argument means that it will be executed in an interactive mode – it keeps the STIN open

Explore the operating system of our newly created container:
----
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
----

=== Running Containers in Interactive Mode
----
$ docker run -it ubuntu:18.04
----

 –rm argument when starting a container in interactive mode, thus will remove the container when we exit:

----
$ docker run -it --rm ubuntu:18.04
----

=== Keep a Container Running
----
$ docker run -d ubuntu:18.04 tail -f /dev/null
----
With this command, we are starting a new container in detached/background mode (-d) and executing the tail -f /dev/null command inside the container. As a result, this will force our container to run forever.

----
$ docker exec -it CONTAINER_ID sh
----

Source: https://www.baeldung.com/ops/docker-container-shell[Docker container shell]

== Setting Memory And CPU Limits

=== Setting Resources Limit With docker run
==== Memory
To constrain memory, we need to use the m parameter:
----
$ docker run -m 512m nginx
----

Set a soft limit called a reservation. It's activated when docker detects low memory on the host machine:
----
$ docker run -m 512m --memory-reservation=256m nginx
----

==== CPU
Set the CPUs limit using the cpus parameter
----
$ docker run --cpus=2 nginx
----

Specify the priority of CPU allocation. The default is 1024, higher numbers are higher priority:
----
$ docker run --cpus=2 --cpu-shares=2000 nginx
----

=== Setting Memory Limit With the docker-compose File
==== Versions 3 and Newer With docker swarm
----
services:
  service:
    image: nginx
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 512M
            reservations:
              cpus: 0.25
              memory: 128M
----

To take advantage of the deploy segment in a docker-compose file, we need to use the docker stack command. To deploy a stack to the swarm, we run the deploy command:
----
$ docker stack deploy --compose-file docker-compose.yml bael_stack
----

==== Version 2 With docker-compose

----
service:
  image: nginx
  mem_limit: 512m
  mem_reservation: 128M
  cpus: 0.5
  ports:
    - "80:80"
----

To create configured containers, we need to run the docker-compose command:
----
$ docker-compose up
----

=== Verifying Resources Usage

----
$ docker stats
CONTAINER ID        NAME                                             CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
8ad2f2c17078        bael_stack_service.1.jz2ks49finy61kiq1r12da73k   0.00%               2.578MiB / 512MiB   0.50%
----

Source: https://www.baeldung.com/ops/docker-memory-limit[Docker Memory Limit]

== Listing containers
*“docker ps” or “docker container ls”*

=== Running Containers

----
docker container ls
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                NAMES
1addfea727b3        mysql:5.6            "docker-en.."   2 seconds ago       Up 1 second         0.0.0.0:32801->3306/tcp              dazzling_hellman
----

* “CONTAINER ID” is the container unique identifier. This identifier is the truncated version of a pretty long SHA-256 hash
* “COMMAND” is the command responsible for running the container

* PORT external/host: internal/container

=== All Containers
----
$ docker container ls -a
CONTAINER ID        IMAGE                STATUS
1addfea727b3        mysql:5.6            Up 4 hours
32928d81a65f        mysql:5.6            Exited (1) 4 hours ago
----

=== Latest Containers
To see the last n Docker containers (both running and stopped), use the -n <number> or –last <number>
----
$ docker container ls -n 2
CONTAINER ID        IMAGE               STATUS
1addfea727b3        mysql:5.6           Up 4 hours
32928d81a65f        mysql:5.6           Exited (1) 4 hours ago
----

=== Disabling Truncation
----
$ docker container ls --latest --no-trunc
CONTAINER ID                                                       COMMAND
1addfea727b38f484a2e0023ed7f47dcb9bbfc6e053f094c349391bb38cb3af7   "docker-entrypoint.sh mysqld"
----

=== Quiet Mode
To see the container id of the containers
----
$ docker container ls -q
1addfea727b3
09c4105cb356
----

=== Container Size
----
$ docker container ls --latest -s
CONTAINER ID        IMAGE               SIZE
1addfea727b3        mysql:5.6           2B (virtual 256MB)
----
The first value (2B) represents the number of bytes that are used for the *writable layer* of each container. The second value is the image size on disk, which is 256 MB in this case.

=== Customized Output
----
$ docker container ls --format "{{.ID}} -> Based on {{.Image}}, named {{.Names}}, ({{.Status}})"
1addfea727b3 -> Based on mysql:5.6, named dazzling_hellman, (Up 3 hours)
09c4105cb356 -> Based on nats:2.1.0-scratch, named nats-1, (Up 4 hours)
----

=== Advanced Filtering
*-f or –filter option*

----
$ docker container ls --filter "status=exited"
CONTAINER ID        IMAGE               STATUS
32928d81a65f        mysql:5.6           Exited (1) 8 hours ago

$ docker container ls --filter "status=exited" --filter "exited=1"
CONTAINER ID        IMAGE               STATUS
32928d81a65f        mysql:5.6           Exited (1) 8 hours ago
----

Pause a container

----
$ docker container pause redis-2

$ docker container ls --filter "status=paused"
CONTAINER ID        IMAGE               STATUS
4cf774b9e4a4        redis:5             Up 45 minutes (Paused)
----

Docker container possible statuses — created, restarting, running, removing, paused, exited, or dead.

Filer by name:
----
$ docker container ls -a --filter "name=pg"
CONTAINER ID        IMAGE               STATUS
b06cfe3053e5        postgres:11         Up 18 minutes
16d3c67ebd40        postgres:11         Exited (0) 9 hours ago
----

Filter by base image
----
$ docker container ls -a --filter "ancestor=postgres"
CONTAINER ID        IMAGE               STATUS
b06cfe3053e5        postgres:11         Up 28 minutes
16d3c67ebd40        postgres:11         Exited (0) 9 hours ago
----

=== To force delete all containers
----
$ docker container rm -f $(docker container ls -aq)
----

Source: https://www.baeldung.com/docker-images-vs-containers[Docker images]






