= Advanced questions

Sources

* https://arc.dev/developer-blog/java-interview-questions/
* https://www.fullstack.cafe/blog/advanced-java-interview-questions
* https://www.edureka.co/blog/interview-questions/java-interview-questions/

== Topics

* https://www.fullstack.cafe/blog/hashing-interview-questions[Hashing]
* https://www.fullstack.cafe/blog/dependency-injection-interview-questions[Dependency injection]
* https://www.fullstack.cafe/blog/microservices-interview-questions[Microservices]
* https://www.fullstack.cafe/blog/data-structures-interview-questions[Data structures]
Which data structure will you choose to model a ranges number?
* https://www.fullstack.cafe/blog/domain-driven-design-interview-questions[DDD]
* https://www.fullstack.cafe/blog/kubernetes-interview-questions[kubernetes]





== Design patterns

* an efficient way to implement a singleton pattern in Java

After Java 5
----
public enum COLOR {
    INSTANCE;
    private final String[] favoriteColors =
            { "green", "blue" };
    public void printFavorites() {
        System.out.println(Arrays.toString(favoriteColors));
    }
}
----
* equivalent to the public field approach, except that it is more concise, provides the serialization machinery for free, and provides an ironclad guarantee against multiple instantiation, even in the face of sophisticated serialization or reflection attacks.

== Concurrency

* What does synchronized mean?

The synchronized keyword is all about different threads reading and writing to the same variables, objects and resources. The synchronized keyword is one of the tools that make your code thread safe.
So simply speaking when you have two threads that are reading and writing to the same 'resource', say a variable named foo, you need to ensure that these threads access the variable in an atomic way. Without the synchronized keyword, your thread 1 may not see the change thread 2 made to foo, or worse, it may only be half changed. This would not be what you logically expect.


== Caching

* What is Caching

a cache is a high-speed data storage layer which stores a subset of data, typically transient in nature, so that future requests for that data are served up faster than is possible by accessing the data’s primary storage location. Caching allows you to efficiently reuse previously retrieved or computed data.

* Cache Writing Strategies

*Pre-caching data* - for small pieces of data, usually during the application initialization, before any request.
*On-demand* - checking first if the requested data is in the cache (if the data is found, it is called a cache hit), using it, improving the performance of the application. Whenever the requested data has not been written to the cache (cache miss), the application will need to retrieve it from the slower source, then writing the results in the cache, thus saving time on subsequent requests for the same data.

* What is Cache Invalidation

Cache invalidation gives you the best of both worlds: you can have very long TTLs, so when content changes little, it can be served from the cache because no requests to your application are required. At the same time, when data does change, that change is reflected without delay in the web representations.

*Purge* - Removes content from cache immediately. When the client requests the data again, it is fetched from the application and stored in the cache. This method removes all variants of the cached content.

*Refresh* - Fetches requested content from the application, even if cached content is available. The content previously stored in the cache is replaced with a new version from the application. This method affects only one variant of the cached content.

*Ban* - A reference to the cached content is added to a blacklist (or ban list). Client requests are then checked against this blacklist, and if a request matches, new content is fetched from the application, returned to the client, and added to the cache. This method, unlike purge, does not immediately remove cached content from the cache. Instead, the cached content is updated after a client requests that specific information.

* What usually should be cached?

** Long-running queries on databases,
** high-latency network requests (for external APIs),
** computation-intensive processing


== Microservices

* API Gateway pattern

An API Gateway is a server that is the single entry point into the system. It is similar to the Facade pattern from object‑oriented design. The API Gateway encapsulates the internal system architecture and provides an API that is tailored to each client. It might have other responsibilities such as authentication, monitoring, load balancing, caching, request shaping and management, and static response handling.

Therefore, the API gateway sits between the client apps and the microservices. It acts as a reverse proxy, routing requests from clients to services. It can also provide other cross-cutting features such as authentication, SSL termination, and cache.




