= Java Core

== What is difference between Heap and Stack Memory in java?
*Java Heap Space*

Java Heap space is used by java runtime to allocate memory to Objects and JRE classes. Whenever we create any object, it’s always created in the Heap space.

Garbage Collection runs on the heap memory to free the memory used by objects that doesn’t have any reference. Any object created in the heap space has global access and can be referenced from anywhere of the application.

*Java Stack Memory*

Stack in java is a section of memory which contains methods, local variables and reference variables. Local variables are created in the stack.

Stack memory is always referenced in LIFO (Last-In-First-Out) order. Whenever a method is invoked, a new block is created in the stack memory for the method to hold local primitive values and reference to other objects in the method.

As soon as method ends, the block becomes unused and become available for next method. Stack memory size is smaller compared to Heap memory.

== What do you understand by Java Memory Model?
=== Memory Barrier
==== A read barrier
invalidates the local memory (cache, registers, etc) and then reads the contents from the main memory, so that changes made by other threads becomes visible to the current Thread.

==== A write barrier
flushes out the contents of the processor’s local memory to the main memory, so that changes made by the current Thread becomes visible to the other threads.

=== JMM semantics for synchronized
When a thread acquires monitor of an object, by entering into a synchronized block of code, it performs a read barrier (invalidates the local memory and reads from the heap instead).

Similarly exiting from a synchronized block as part of releasing the associated monitor, it performs a write barrier (flushes changes to the main memory)

Thus modifications to a shared state using synchronized block by one Thread, is guaranteed to be visible to subsequent synchronized reads by other threads. This guarantee is provided by JMM in presence of synchronized code block.

=== JMM semantics for Volatile fields
Read & write to volatile variables have same memory semantics as that of acquiring and releasing a monitor using synchronized code block. So the visibility of volatile field is guaranteed by the JMM.

Thus when Thread A writes to a volatile variable V, and afterwards Thread B reads from variable V, any variable values that were visible to A at the time V was written are guaranteed now to be visible to B.

----
Data data = null;
volatile boolean flag = false;

Thread A
-------------
data = new Data();
flag = true;  <-- writing to volatile will flush data as well as flag to main memory

Thread B
-------------
if(flag==true) { <-- reading from volatile will perform read barrier for flag as well data.
use data;  <--- data is guaranteed to visible even though it is not declared volatile because of the JMM semantics of volatile flag.
}
----

== What is a Memory Leak? How can a memory leak appear in garbage collected language?
The standard definition of a memory leak is a scenario that occurs when objects are no longer being used by the application, but the Garbage Collector is unable to remove them from working memory – because they’re still being referenced. As a result, the application consumes more and more resources – which eventually leads to a fatal OutOfMemoryError.

*Types of Memory Leaks in Java*

* Memory Leak through static Fields
* Unclosed Resources/connections
* Adding Objects With no hashCode() and equals() Into a HashSet
* Inner Classes that Reference Outer Classes
* Through finalize() Methods
* Calling String.intern() on Long String

== What will be the problem if you do not override hashcode() method?

Some collections, like HashSet, HashMap or HashTable use the hashcode value of an object to find out how the object would be stored in the collection, and subsequently hashcode is used to help locate the object in the collection. Hashing retrieval involves:

* First, find out the right bucket using hashCode().
* Secondly, search the bucket for the right element using equals()

If hashcode() in not overridden then the default implementation in Object class will be used by collections. This implementation gives different values for different objects, even if they are equal according to the equals() method.

== What is Immutable Class in Java

When the state of object can not be changed after its construction then the object is called Immutable.

=== Benefits of Immutable Objects
==== Inherent thread-safety
Immutable objects are inherently thread-safe, thus help writing multi-threading code without much worries.

==== Cacheability
Because Immutable objects do not change their value, we can freely cache them and be confident that their value won’t change.

==== Good candidate for Hashing Keys
Immutable objects are good candidate for hash keys because their hashcode can be cached and reused for better performance. They make the best HashMap keys.

=== Guidelines for Making a class Immutable
* All fields should be declared final

* Class itself is declared final so that the derived classes do not make it Mutable.

* this reference should not be allowed to escape during object construction such as in anonymous inner classes (for example adding action listener)

* Any field that contains reference to mutable objects (such as arrays, collections, StringBuffer, etc)

    ** Are private

    ** Are never returned or exposed to the caller

    ** Are the only reference to the Objects that they refer

    ** Do not change the state of the referenced object after the construction.

    ** If mutable fields must be returned to the caller, then a defensive copy should be returned so that the changes do not reflect in the inner data structure.
For example,

        *** Defensive copy of mutable object

        ----
        public List getList() {
        return Collections.unmodifiableList(list);
        }
        ----
defensive copy of the mutable field before returning it to caller

        *** If a mutable Object is passed in the constructor (like an array), then Immutable class should first make a defensive copy of the mutable object before storing its reference.

