= Cloud computing

== Types of Cloud computing services

* On Premises

Layers: all managed in house
Applications
Data
Runtime
Middleware
OS
Virtualization
Servers
Storage
Networking


* Infrasturture as a service - IaaS +
Azure/ AWS

Layers:
Applications
Data
Runtime
Middleware
OS
''''
Virtualization
Servers
Storage
Networking

* Platform as a Service - PaaS +
Azure Logic Apps, Heroku, Amazon Elastic Beanstalk

Layers:
Applications
Data
''''
Runtime
Middleware
OS
Virtualization
Servers
Storage
Networking

* Software as a Service
Office 365, Google G Suite, Safesforce

Layers: all managed by vendor
Applications
Data
Runtime
Middleware
OS
Virtualization
Servers
Storage
Networking

== Cloud computing Deployment Models
* Public Cloud +
Cloud services provided by a thrird-party provider, hardware can be shared amongst multiple clients. 
* Private Cloud +
Hardware is only used by a single company, which often owns the hardware and datacenter
* Hybrid Cloud + 
Combination of public and private cloud with automation and orchestration between the two
* Community Cloud +
Infrastructure is shared between several orgs from specific community with common concerns (security, compliance, jurisdiction)


