= Authentication

== Broken Authentication

*Vultneabilities*

1. missing authetication for critical function
Solution - check authentication for each operation and have in place security tests (automated) to check the operations
2. improper restriction of excessive authentication attempts
  Countermeasures:
  - add delay: constant, back-off algortithms, hashing rounds
  - disconnect user
  - add chanllenge: captcha, MFA, TAN-code
  - banning remote hosts - by IP address
  
3. Use of hard-coded credentials

Inbound

Authentication mechanism checks input against hard-coded data
Solution- first login mode

Outbound

Connects to another system using hard-coded credentials for that system
Solution
If any key needs to be stored, encrypt the key itself.
Decryption can be only done at statup or runtime.

Using API keys
- don't embeded api keys in code
- don't store api keys in same git repo
- allow api keys to be used from trusted sources - source ip / signed mobile apps
- implemnt api key revocation/expiration

== Seurity Misconfiguration 

1. Execution with unnecessary privileges -> *Least privilege principle*

2. Incorrect permission assignment for Critical resources

Unix permission model (user, group, other)
Read Write Execute

umask u=rw, g-rwx, o-rwx

Access Control Lists (ACL's)

== Missing Function Level Access Control

1. Missing Authorization
GET/addUser -> isAuthenicated-> isAuthorized-> addUser

2. Incorrect Authorization
Solution: add tests/ add logging


= Encryption

Encryption = Plain text + key .. algorithm ... cipher text
Decryption = Cipher text + key .. algorithm ... plain text

Cryptography objectives
* Confidentiality - only the intended receiver can read the data 
* Integrity - the receiver can determine if the data has been altered
* Authenticity - the sender can be verified
* Non-repudiation - the sender cannot deny sending the data

== Missing Encryption

- expose sensitive data 
Mitigation: check if you need to store/transmit sensitive data and if needed use proper encryption

When to use encryption:
- for sensitive data: credentials, personal data, banking/financial data

Ensure data is secure: in transit, in storage, in the users browsers





