= Authentication

== Broken Authentication

*Vultneabilities*

1. missing authetication for critical function
Solution - check authentication for each operation and have in place security tests (automated) to check the operations
2. improper restriction of excessive authentication attempts
  Countermeasures:
  - add delay: constant, back-off algortithms, hashing rounds
  - disconnect user
  - add chanllenge: captcha, MFA, TAN-code
  - banning remote hosts - by IP address
  
3. Use of hard-coded credentials

Inbound

Authentication mechanism checks input against hard-coded data
Solution- first login mode

Outbound

Connects to another system using hard-coded credentials for that system
Solution
If any key needs to be stored, encrypt the key itself.
Decryption can be only done at statup or runtime.

Using API keys
- don't embeded api keys in code
- don't store api keys in same git repo
- allow api keys to be used from trusted sources - source ip / signed mobile apps
- implemnt api key revocation/expiration

== Security Misconfiguration

1. Execution with unnecessary privileges -> *Least privilege principle*

2. Incorrect permission assignment for Critical resources

Unix permission model (user, group, other)
Read Write Execute

umask u=rw, g-rwx, o-rwx

Access Control Lists (ACL's)

== Missing Function Level Access Control

1. Missing Authorization
GET/addUser -> isAuthenicated-> isAuthorized-> addUser

2. Incorrect Authorization
Solution: add tests/ add logging


= Encryption

Encryption = Plain text + key .. algorithm ... cipher text
Decryption = Cipher text + key .. algorithm ... plain text

Cryptography objectives
* Confidentiality - only the intended receiver can read the data 
* Integrity - the receiver can determine if the data has been altered
* Authenticity - the sender can be verified
* Non-repudiation - the sender cannot deny sending the data

== Missing Encryption

- expose sensitive data 
Mitigation: check if you need to store/transmit sensitive data and if needed use proper encryption

When to use encryption:
- for sensitive data: credentials, personal data, banking/financial data

Ensure data is secure: in transit, in storage, in the users browsers

== Use the wrong encryption algorithms

Use strong algorithms
- RSA, AES for public key cryptography - with strong enough keys
- SHA-256 or better for hashing
- use password specific algorithms for encrypting passwords - PBKDF2, bcrypt, scrypt

Weak algorithms
- DES -> replaced with AES
- MD5, SHA-1

=== Salt

A hacker can use a rainbow table - to lookup the password for this hash value
Adding a salt before hashing -> will change the hash for each password.

- make a salt long enough
- use a unique salt for every user 

=== Key management
- use long keys
- store your keys safely

= Injection 

can go to root level access 

Risks:
- impersionate specific users or bypass authentication
- disclosure data residing on a DB server
- alter/delete data stored in a DB
- execute OS commands on the DB server
- upload files and reading files from filesystem
- obtain shell access

Detection:
- uses an interpreter
- verify untrusted data( user input fields, URL, uploaded configuration filesm cookie data, data received from other applications/API's)

Mitigation:

Good practices:

- never trust client side data
- use least privilege when connecting to the DB and other backend system
- remove information from error messages

Defence options:
- prepared statements (with parametrized queries)
- stored procedures
- input validation

== Prepared statements 
Prepare a query with parameter placeholders, bind variables the execute

== Stored procedures

== Input Validation

Do not: 
- depend on client side valdiation
- verify what is not allowed and reject it - blackist

Do:
- verify what is allowed and accept it - whitelist
- use trusted libraries
- check ranges, check for strange characters
- perform input validation on all input( cookies, hidden variables)
- don't use parameters that aren't necessary


= Path Traversal

Manipulation of user-controlled variables thare are used to reference files, in order to access critical files/directories on the server.

Risks:
- information disclosure
- remote code execution
- local or remote service enumeration
- local or remote file inclusion
- CIA compromise

Any of the methods
- java.io.FileInputStream()
- java.io.FileOutputStream()
- java.io.File()

- check if ../ is contained in the input (%2e, ...../ and all combinations )

SecurityManager(Security Exception)
----
grant codeBase "file:${{java.ext.dirs}}/*" {
    permission java.security.AllPermission;
};
----

By default, the JVM loads the common system policy file located at <java.home>/lib/security/java.policy. If we've defined any user-local policy in  <user.home>/.java.policy, the JVM appends it to the system policy.

It's also possible to specify policy file via command line: –Djava.security.policy=/my/policy-file. That way we can append policies to the previously loaded system and user policies.

There is a special syntax for replacing all system and user policies (if any) – double equals sign: –Djava.security.policy==/my/policy-file
Source: https://www.baeldung.com/java-security-manager

- or use a lookup table to check for filenames available

Restrict application in its env:
- chroot/jain/container

Specific mitigation:
- web application firewall
- api methodology

= Cross-site scripting

A malicious script is injected into a trusted website.
Can happen whe user-supplied input is shown in a page withous using proper validation and encoding. 

Types:
- non-persistent cross-site scripting(reflected)
- persistent cross-site scripting(stored)
- dom based cross-site scripting

Risks of XSS:
- session hijacking
- installation of malware
- redirect the user to another page
- modify the DOM tree
- obtain shell access

Mitigation
Never put untrusted data:
- directory in a script <script> ... </script>
- inside a HTML comment <!-- .. --> 
- in an attribute name <div .... = test/>
- in a tag name <... href ="/aaa"/>
- directly in CSS <style> .. </style>

Input validation
Validateon: type of characters /\<>"', length, algorithm
- use a whitelist

- use context specific output encoding

- user input for an URL -> encode for URL
- used in an HTML attribute -> encode for HTML attribute


= Distributed Denial of Service

type of attack that uses a number of hosts to overwhelm a target, causing perfomance issues on the servers and in the end system crash and therefore make the service unavailable. 

SYN Flood - most populat attack. (Infrastructure attacks)

Also HTTP attacks can occur. (Application attacks)
GET Flodd, POST Flood, Http Header Flood(Cookie)

Mitigation
- write DoS resilient code
- monitor
- isolate failures
- scale smartly

Http Flood attack - mitigation
- rate-limiting 
- use javascript challenge to knock down HTTP bots
- make use of a CDN and (Cloud) WAF


= Threat modeling

Identify threats, part of the Software Development Lifecycle - SDLC

* Spoofing - authenticity guaranteed
* Tampering - integrity guaranteed
* Information disclosure - prevent privacy breackes and data leaks
* Denial of Service - availability guaranteed
* Elevation of privilege - authorization be guaranteed


= Certificates

- Symmetric encyption
- Asymmetric encyption

each party has their own key pair: private + public

Encryption of data - using receiver's public key. 

Certificate = public key signed by a trusted CA (3rd party)

== Hashing

A hash - math function -> generates a unique string.
The hash will change completely with any modification of the input. 

== Signing

The message hash is encrypted using the senders private key. 
The receiver decrypts the received hash and compares to their own hash. 

Public key + metadata + trusted CA signature = certificate

Steps:
1. Install and configure app
2. generate a key pair
3. generate a CSR cert signing request for public key 
4. Submit CSR to your CA
5. Retrieve and install the signed certificates

Subject names in the certificate matter. 

* keys + certificate - not part of the code, and should not be in git repo, or installer packages
* key pairs should be generated on the target system 
* private keys should be password protected

*Key compromise*

- contact CA for revocation of your certificate
- resecure your application
- create new key pairs
- get new certificates

PKI = trust 

Trust store = location to store trusted Certificate Authorities













