ifndef::imagesdir[:imagesdir: ../images]
= Cryptography

== Purpose
- Nonrepudiation - can't claim it was not send by you
- Integrity - is the data you sent
- Authentication
- Confidentiality

=== Process
Plaintext + Encryption = Chiphertext
Chipertext + Descryption = Plaintext

== Types of Cryptography
=== Symmetric
Pro

- both parties use the same key
- super fast
- easy to implement
- key isn't transmitted with data

Not good

- key has to be distributed to all parties
- manageability
- look out for Dictionary Attacks
- hard to prove authenticity

=== Asymmetric
Pro

- two keys required (public and private)
- digital signature
- better security

Not good

- slower and more CPU power
- not good id the private key is exposed
- MiTM and Brute force attacks
- No decryption if the private key is lost

Government Access to Key (GAK)

== Ciphers

Types: Classical and Modern

Classical: Substitution, Transposition

Modern: Symmetric, Asymmetric, Block, Stream

Algorithms:

DES Data Encryption Standard
64-bit blocks, 56-bit key for encryption/decryption

3DES - 3 des with 3 keys (K1, K2, K3)

AES - Advanced Encryption Standard - symmetric key algorithm
128-bit blocks , 128/192/256 bit keys
- encrypting data that is not classified

RC4 - variable key size, symmetric
- not that good, was used part of wep

Blowfish - symmetric block
- same key to encrypt/decrypt
- 64-bit blocks, 32-448 bit key
- advantage - speed

Twofish - 128-bit block
- 256-bit key
- single key

== Standards and Protocols

DSA - 320-bit for signatures/512-1024 bit for security/ Private-Public keys

RSA - Uses two large prime numbers

Deffie-Hellman - Allows two parties to form a shared key over a public network

== Hashes
- check a document was not changed
- a document receives a digital signature
- Message Digest - MD - 128-bit hash value (foundation MD2, MD4,MD5)
- SHA-1 - Secure Hash Algorithm - takes the input -> 160-bit -> hex, used with PGP, TLS, SSH, SSL
- SHA-2 - similar tu SHA1-1, stronger
- SHA-3 - sponge construction, XORed

Tool: Sysinternals

=== Designed for Messages
HMAC - embedded hash function
CHAP - PPP, 3-way handshake
EAP - Passwords, One-Time passwords(OTP), ID cards, Smart Tokens

== Cryptography tools

=== MD5 Hash Calculators
- bullzip.com
- nirsoft.net
- onlinemd5.com
- Microsoft FCIV

=== Folder/Files
- EFS - from windows
- 7zip
- GnuPG -- Windows Kleopatra, create new key pair
- AxCrypt

=== Drives
- BitLocker
- VeraCrypt
- FileVault
- GNOME Disk Utility

=== Mobile devices
- MD5 Checker
- Hash Droid
- Last Pass

== PKI Public Key Infrastructure
- Asymmetric Using Two keys
- Certificate management System - CMS
- Digital certificates
- Validation Authority (VA)
- Certificate Authority (CA) - issues/verifies certificates
- Registration Authority (RA) - verifies the CAs

Encrypt a message with a public key of the receiver.
Receiver uses the private key to decrypt the email and read it.

CA - issues digital certificates - trusted 3rd party
Verisign, thawte, Entrust, GoDady, DigiCert
- issues, revoking, distributes certificates

Certificate - identifying a user/org, public key, alg, issuer, subject name

Signed certificate - signed by a public CA, private key is kept secret by the CA
Self-signed certificate - signed by the same org

== Encrypting Emails, File and Disk drives

=== Digital Signatures
Verify an email was send by the real person.
The email is signed with the private key of the sender,
and is verified with the public key of the sender by the receiver.

=== SSL Secure Sockets Layer
- private channel
- authenticated channel
- reliable channel
- uses asymmetric and symmetric

Client sends Client Hello + random number + cipher alg supported
Server replies Server Hello + select alg + random number (ask certificate from the client)
Client - creates a random pre master secret and encrypts with the public key of the server








