= Cybersecurity

Git repo: https://github.com/The-Art-of-Hacking/h4cker

Certification map: https://pauljerimy.com/security-certification-roadmap/

== Concepts
A *vulnerability* is an exploitable weakness in a system or its design.

Vulnerabilities can be found in protocols, operating systems, applications, hardware, and system designs.

List vulnerabilities: https://owasp.org/www-community/vulnerabilities/

Vendors, security researchers, and vulnerability coordination centers typically assign vulnerabilities an identifier that’s disclosed to the public - *Common Vulnerabilities and Exposures* (CVE).

An *exploit* is software or a sequence of commands that takes advantage of a vulnerability in order to cause harm to a system or network.

A *threat* is any potential danger to an asset.

A *countermeasure* is a safeguard that somehow mitigates a potential risk.

=== CIA Triad

==== Confidentiality
Confidentiality is the property, that information is not made available or disclosed to unauthorized individuals, entities, or processes.

No1 -> Encryption

* Data In Transit - tls
* Data at Rest - encrypt
* Data in Use

=== Integrity
Integrity is the ability to make sure that a system and its data has not been altered or compromised.

It ensures that the data is an accurate and unchanged
representation of the original secure
data.

Hashing (signing)

=== Availability

Availability refers that a system or application must be “available” to authorized users at all times.


Common Vulnerability Scoring System (CVSS) - uses CIA triad

== Attacks

=== Basic Port Scan
Involves scanning a predetermined TCP/UDP port by sending a specifically configured packet that contains the port number of the port that was selected.

=== TCP Scan
A TCP-based scan of a series of ports on a machine to determine port availability.

=== TCP SYN Scan
The scanner sends a SYN packet, and if the target responds with a SYN-ACK packet, the scanner typically responds with an RST packet.

=== TCP ACK Scan
 TCP ACK scans are typically used when trying to see if a firewall is deployed and its rule sets.

=== Stealth Scan
Designed to go undetected by network auditing tools

=== Social Engineering

This could be done through email or misdirection of web pages, which results in the user clicking something that leads to the attacker gaining information.

=== Phishing

Wheretheattackerpresentsalink that looks like a valid, trusted resource to a user. +
When the user click sit,he is prompted to disclose confidential information such as his username and password.

=== Pharming

The attacker uses this technique to direct a customer’s URL from a valid
resource to a malicious one that could be made to appear as the valid site to the user.

=== Malvertising
The act of incorporating malicious ads on trusted websites

=== Privilege Escalation Attacks

Privilege escalation is the process of taking some level of access (whether authorized or not) and achieving an even greater level of access (elevating the user’s privileges).

=== Backdoors
A backdoor application can be installed by the attacker to either allow future access or collect information to use in further attacks.

=== Code execution
One of the most devastating actions available to an attacker is the ability to execute code within a device.

=== Man-in-the Middle Attacks
The main purpose is eavesdropping, so the attacker can see all the traffic.

=== Denial-of- service (DoS) and distributed DoS (DDoS)
• DirectDDoSattacks
• Reflected
• AmplificationDDoSattacks

=== Spoofing Attacks
A spoofing attack is when an attacker impersonates another device to execute an attack.

=== Password Attacks
Password-resetting attacks

Password cracking:
the attacker needs tools such as extractors for hash guessing, rainbow tables for looking up plaintext passwords, and password sniffers to extract authentication information.

Password sniffing:
The threat actor just sniffs authentication packets between a client and server and extracts password hashes or enough authentication information to begin the cracking process.

Password capturing:
This is typically done by using key loggers or Trojan horses.

=== Wireless Attacks

The attacker basically installs an access point and can create a backdoor and obtain access to the network and its systems.

Evil twin attack:
Basically the attacker purchases a wireless access point, plugs it into the network, and configures it exactly the same as the existing network.

Bluejacking:
The attacker sends unsolicited messages to another device via Bluetooth.

IV attack:
The attacker can cause some modification on the Initialization Vector (IV) of a wireless packet that is encrypted during transmission.

== Public Key Cryptography

A *cipher* is a set of rules, which can also be called an algorithm, about how to perform encryption or decryption.

=== Symetric encryption

Block ciphers +
A block cipher is a symmetric key cipher (meaning the same key is used to encrypt and decrypt) that operates on a group of bits called a block.

Examples:

* Advanced Encryption Standard (AES)
* Triple Digital Encryption Standard (3DES)
* Digital Encryption Standard (DES)
* Blowfish

Stream cipher +
A stream cipher is a symmetric key cipher (meaning the same key is used to encrypt and decrypt), where the plaintext data to be encrypted is done a bit at a time against the bits of the key stream, also called a cipher digit stream.

=== Asymmetric Algorithms

An example of an asymmetric algorithm is a public key algorithm.
Use two different keys that mathematically work together as a pair
Examples: RSA, Diffie-Hellman, DSA, ElGamal

=== Hashing

Hashing is a method used to verify data integrity.

* one-way function

|===
|Algorithm |Operation |Status |Alternative |QCR - quantum computer resistant

|DES	|Encryption	|Avoid	|AES	|—
|3DES	|Encryption	|Legacy	|AES	|—
|RC4	|Encryption	|Avoid	|AES	|—
|AES-CBC mode |Encryption |Acceptable |AES-GCM |✓ (256-bit)
|AES-GCM mode |Authenticated encryption |NGE |— |✓ (256-bit)

|DH-768, -1024  |Key exchange |Avoid   |DH-3072 (Group 15) |-
|RSA-768, -1024 |Encryption   |Avoid   |RSA-3072 |-
|DSA-768, -1024 |Authentication |Avoid |DSA-3072 |-

|DH-2048  |Key exchange    |Acceptable  |ECDH-256  |-
|RSA-2048 |Encryption      |Acceptable  |—         |-
|DSA-2048 |Authentication  |Acceptable  |ECDSA-256 |-

|DH-3072  |Key exchange  |Acceptable  |ECDH-256  |-
|RSA-3072 |Encryption    |Acceptable  |- |-
|DSA-3072 |Authentication |Acceptable |ECDSA-256 |-

|MD5	|Integrity	|Avoid	|SHA-256	|—
|SHA-1 |Integrity |Legacy |SHA-256 |—

|SHA-256 |Integrity |NGE |SHA-384 |-
|SHA-384 |Integrity |NGE |- |✓
|SHA-512 |Integrity |NGE |- |✓

|HMAC-MD5	|Integrity	|Legacy	|HMAC-SHA-256	|—
|HMAC-SHA-1	|Integrity	|Acceptable	|HMAC-SHA-256	|—
|HMAC-SHA-256	|Integrity	|NGE	|—	|✓

|ECDH-256  |Key exchange   |Acceptable |ECDH-384 |—
|ECDSA-256 |Authentication |Acceptable |ECDSA-384 |—

|ECDH-384 |Key exchange |NGE |- |-
|ECDSA-384 |Authentication |NGE |- |-

|===

QCR = quantum computer resistant. +
NGE = next generation encryption.


== Incident response
A computer security incident is a violation or imminent threat of violation of computer security policies, acceptable use policies, or standard security practices.

==  Network and Host Telemetry
Logs from network devices such as firewalls, routers,
and switches can prove useful when you’re proactively detecting or responding to a security incident.

For example, brute-force attacks against a router, switch, or firewall can be detected by system log (syslog) messages that could reveal the suspicious activity.

*Syslog* messages from transit network devices can provide insight into and context for security events that might not be available from other sources.

NetFlow provides detailed network telemetry

Internet Protocol Flow Information Export (IPFIX) is a network flow standard. +
IPFIX was created to create a common, universal standard of export for flow information from routers, switches, firewalls, and other infrastructure devices.

Open Source NetFlow Analysis Tools:

• NFdump
• SiLK
• ELK
• https://github.com/robcowart/elastiflow

Network Packet Capture:

• tcpdump, which is an open source packet capture utility that runs on Linux and Mac OS X systems
• Wireshark, which is one of the most popular open source packet capture utilities used by many professionals
• Netscout enterprise packet capture solutions

==  Security Monitoring

• Location based on just the IP address of the endpoint or DNS hostname
• Application logs
• Processes running on the machine
• Personal firewalls
• Intrusion detection/prevention systems
• Antivirus or antimalware
• Web security logs (from a web security appliance)
• Email security logs (from an email security appliance)
• Advanced malware protection logs

• Mandatory password protection
• Jailbreak detection
• Remote wipe
• Remote lock
• Device encryption
• Data encryption
• Geolocation
• Malware detection
• VPN configuration and management
• Wi-Fi configuration and management

*Data normalization* is the process of capturing, storing, and analyzing data (security-related events, in this case) so that it exists in only one form.

Security Information and Event Management (SIEM)

5-Tuple: Source IP Address, Source Port, Destination IP Address, Destination Port, Protocol

==  Access Control Models
Access controls are used in the process of granting, preventing, or revoking access to an object.

=== Identification
A secure identity should be unique in the sense that two users should be able to identify themselves unequivocally.

=== Authentication
Authentication is the process of proving the identity of a subject or user.

* Authentication by knowledge

e.g: a user providing a password
The disadvantage of using this method is that once the information is lost or stolen, an attacker would be able to successfully authenticate.

* Authentication by Ownership

e.g. use of a token or smart card

* Authentication by Characteristic - biometric

=== Multifactor Authentication

An authentication system is considered strong if it uses at least two different authentication methods.

=== Authorization
A policy or rule needs to be established to describe in which cases a subject should be able to access the resource.

• *Implicit deny*: If no rule is specified for the transaction of the subject/object, the authorization policy should deny the transaction.
• *Need to know*: A subject should be granted access to an object only if the access is needed to carry out the job of the subject.

=== Accounting

Accounting is the process of auditing and monitoring what a user does once a specific resource is accessed.

Commercial classification: Confidential, Private, Sensitive, Public

Access Control Models:

• Discretionary access control (DAC)
• Mandatory access control (MAC)
• Role-based access control (RBAC)
• Attribute-based access control (ABAC)

== Virtual Private Networks (VPNs)

• Point-to-Point Tunneling Protocol (PPTP)
• Layer 2 Forwarding (L2F) protocol
• Layer 2 Tunneling Protocol (L2TP)
• Generic Routing Encapsulation (GRE)
• Multiprotocol Label Switching (MPLS)
• Internet Protocol Security (IPsec)
• Secure Sockets Layer (SSL)








