= Event-Driven Patterns

== Types of events

Content driven events: 

* Atomic/raw native events
A message containing something that occurred as it occurs on a data asset +
Totally depend on the asset technology
Events consumption implies strong coupling with the data assets and that’s why the atomic native events must not be consumed outside of bounded context(service)
* Atomic standard
A standard representation of atomic native events.
Atomic Standard events should be taken in the same way as building blocks REST APIs are. They allow lightly coupled designs by fulfilling a contract between the parts.
* Derived standard
A standardized representation of a business fact, that fulfill certain business needs for a specific purpose, with the same standard representation rules explained before. +
Usually include references to domain entities, but not the entire entity avoiding unnecessary data duplication and event enrichment.
* Derived native
An event that contains derived information in a format and structure tailor-made for a specific consumer or use case, therefore using the native format and definitions of that consumer.

Purpose driven events:
* Command
A message needed in order to communicate any building block with different technical components from other services.
The content is only relevant for an application or domain +
The owner of the schema is always on the consumer side although in the other types of events the owner is the producer.
* Intra-App
Any message needed under the responsibilities of a building block in order to communicate its different technical parts.


== Patterns

Sets of microservices can be logically combined in one bounded context. 

When no new data is created, data is to be consumed from its source using microservices which expose that data.

API composition is to be used as the querying style when aggregating data spanning multiple contexts. + 
CQRS and event sourcing are restricted for use only within a bounded context. 

By constraining CQRS to bounded context the owner of the data can guard the consistency of the data between command and query systems.

CQRS patterns are a natural fit for message based replication of the data. +
Since messages are used for replicating, event sourcing is a natural fit for storing the data. +
However, specific needs of querying may come with specific needs for storage.

Event Sourcing

Event sourcing provides a complete log of every state change ever made to an object, so troubleshooting is easier and it preserves the history of aggregates. +
By expressing the user intent as an ordered log of immutable events, event sourcing gives the business an audit and compliance log which also has the added benefit of providing data provenance. +
It enables resilient applications; rolling back applications amounts to rewinding the event log and reprocessing data. It has better performance characteristics; 
writes and reads can be scaled independently. It enables a loosely coupled application architecture; +
one that makes it easier to move towards a microservices-based architecture.

Event sourcing enables building a forward-compatible application architecture—the ability to add more applications in the future that need to process the same event but create adifferent materialized view.

Store as a Service

Ownership of data -> Any microservice can only directly access its own data. 

Data Consistency 

Orchestration based SAGA +
An orchestrator tells the participants what local transactions to execute. 
This keeps the local services simple and provides clear insight in the orchestration flows. +

Choreography based SAGA +
Each local transaction publishes domain events that trigger local transactions in other services. 
This breaks up and spreads the flow control over all individual services, making it harder to control. +
Correcting failedtransactions and testing these mechanisms becomes very complex

Communication style the consumed services determine the communication style, a SAGA can deal with a mixture of
synchronous and asynchronous, parallel and sequential calls.
Saga comes with complexity, measures are to be taken to protect against potential issues coming from this complexity. 

SAGA principles:
* Set the hardest to compensate transaction at the end of the chain
* Set the most likely to fail transaction at the beginning
* The orchestrator should persistently store state, always but even more so when crossing bounded contexts.
* Participants in a SAGA should provide compensating transactions for their services

A way to thoroughly deal with idempotency in an event-driven architecture could be to implement an identifier generated based on the event content yet with some slight unique logic behind it to guarantee it is not replicated
over systems. If implemented correctly, each consumer would know if it has already processed the event based on the identifier. 

=== Application Patterns

Decomposition -> by business capability

Database architecture:

* shared database - anti-pattern - removes scalability
* database per service - database per bounded context - allowed to have multiple microservices connect to a DB within the same bounded context

Quering:

* API composition
* CQRS - one or more copies of the data are stored in a format optimized for reads. Data replication restrics the use of CQRS to within the boundries of a bounded context. 

Testing:

* Service Integration Contract Test 
* Service Component Test

Data consistency:

* Saga 
* Event sourcing - restrict to use inside bounded context
* Application events/ database triggers/ transaction log tailing - restrict to use inside bounded context

UI:

* Server side page fragment composition - NO
* Client-side UI composition 

Observability:

* Audit Logging
* Application metrics

Cross cutting concerns:

* Externalized configuration

Security:

* JWT

Communication style:

* Messaging 
preference for synchronous communication over bounded contexts for primary calls, the async message based communication - for secondary flows
* Remote procedure invocation

Reliability:

* Circuit Breaker

Discovery:

* Client-side discovery
* Self registration

Observability:

* Distributed tracing
* Health check API
* Exception tracking
* Log Aggregation
* Log deployments and changes

Deployment:

* Multiple services per host
Micro services from multiple bounded contexts can not be combined on a single host, since it would make it impossible to update in isolation. Also scaling for load on a bounded context becomes a challenge. A bounded context owner can choose to combine several micro services of the same context on a single host.
* Single service per host
* Serverless deployment
* Service per container

Discovery:

* Service registry
* Server-side discovery




=== Definitions

Non Blocking 

A system or service that allows access to the resource if it is available otherwise it immediately returns informing the caller that the resource is not currently available
or that the operation has been initiated and not yet completed. +
Asynchronous services are inherently non-blocking. A non-blocking API to a resource allows the caller the option to do other work rather than be blocked waiting on the
resource to become available. +
This may be complemented by allowing the client of the resource to register for getting notified when the resource is available or the operation has completed.

Idempotency

When an operation can be applied multiple times without changing the result beyond the initial operation.
