= Resillience patterns

== Bulkhead

https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead[Bulkhead]

Elements of an application are isolated into pools so that if one fails, the others will continue to function.

=== Context and problem
A cloud-based application may include multiple services, with each service having one or more consumers. 
Excessive load or failure in a service will impact all consumers of the service.

Moreover, a consumer may send requests to multiple services simultaneously, using resources for each request. 
When the consumer sends a request to a service that is misconfigured or not responding, the resources used by the client's request may not be freed in a timely manner. 
As requests to the service continue, those resources may be exhausted. 

Solution
Partition service instances into different groups, based on consumer load and availability requirements. 
This design helps to isolate failures, and allows you to sustain service functionality for some consumers, even during a failure.

