
= Garbage Collector & Memory

* How does Garbage Collection prevent a Java application from going out of memory?

*A*: Garbage Collection simply cleans up unused memory when an object goes out of scope and is no longer needed. However an application could create a huge number of large objects that causes an OutOfMemoryError.

* What is structure of Java Heap?

*Answer*:
The JVM has a heap that is the runtime data area from which memory for all class instances and arrays is allocated. It is created at the JVM start-up. Heap memory for objects is reclaimed by an automatic memory management system which is known as a garbage collector. Heap memory consists of live and dead objects. Live objects are accessible by the application and will not be a subject of garbage collection. Dead objects are those which will never be accessible by the application, but have not been collected by the garbage collector yet. Such objects occupy the heap memory space until they are eventually collected by the garbage collector.

* What is the difference between Serial and Throughput Garbage collector?

*Answer*
The throughput garbage collector uses a parallel version of the young generation collector and is meant to be used with applications that have medium to large data sets. On the other hand, the serial collector is usually adequate for most small applications (those requiring heaps of up to approximately 100MB on modern processors).

* What's the difference between SoftReference and WeakReference in Java?
*Answer*

*Strong reference* - normal reference that protects the referred object from collection by GC. i.e. Never garbage collects.
*Soft reference* - eligible for collection by garbage collector, but probably won't be collected until its memory is needed. i.e. garbage collects before OutOfMemoryError.
*Weak reference* - a reference that does not protect a referenced object from collection by GC. i.e. garbage collects when no Strong or Soft refs.
*Phantom reference* - a reference to an object is phantomly referenced after it has been finalized, but before its allocated memory has been reclaimed.