= Blocking Queue

A blocking queue allows multiple threads to communicate with each other and pass data around. For example, a producer can put items to the queue while consumer can take items out from the queue.

A blocking queue has below characteristics:

* It is always thread-safe

* It can hold arbitrary data

* Producer has to wait if the queue is already full, similarly consumer has to be wait if no item is present in the queue.

== BlockingQueue using intrinsic locking using synchronized keyword

----
class SimpleBlockingQueue {
    final Object[] items = new Object[100]; //1
    int putptr, takeptr, count;

    public synchronized void put(Object x) throws InterruptedException {
        while (count == items.length)
            wait(); //2
        items[putptr] = x;
        if (++putptr == items.length) putptr = 0;
        ++count;
        notifyAll(); //3
    }

    public synchronized Object take() throws InterruptedException {
        while (count == 0)
            wait(); /4
        Object x = items[takeptr];
        if (++takeptr == items.length) takeptr = 0;
        --count;
        notifyAll(); //5
        return x;
    }
}
----

* Max capacity of blocking queue is 100
* We are waiting inside a while loop while queue capacity is full. While loop is required to avoid spurious wakeups.
* All other waiting threads are notified as soon as a new item is added to the queue.
* Consumer thread waits inside a while loop for arrival of new item, if queue is empty. while loop prevents spurious wakeup problem.
* Consumer thread notifies all waiting producer threads as soon as an item is removed from the queue.

== BlockingQueue using Lock and Condition
Lock and Condition interface provides much better flexibility compared to intrinsic locking mechanism, but this flexibility brings more responsibility as we have to take care of calling lock and unlock ourselves. Since one lock can be associated with multiple conditions (notFull & notEmpty in this case), this results in better throughput due to lesser thread contention.

----
class SimpleBlockingQueue {
    final Lock lock = new ReentrantLock();
    final Condition notFull = lock.newCondition();
    final Condition notEmpty = lock.newCondition();
    final Object[] items = new Object[100];
    int putptr, takeptr, count;

    public void put(Object x) throws InterruptedException {
        lock.lock();
        try {
            while (count == items.length)
                notFull.await();
            items[putptr] = x;
            if (++putptr == items.length) putptr = 0;
            ++count;
            notEmpty.signal();
        } finally {
            lock.unlock();
        }
    }

    public Object take() throws InterruptedException {
        lock.lock();
        try {
            while (count == 0)
                notEmpty.await();
            Object x = items[takeptr];
            if (++takeptr == items.length) takeptr = 0;
            --count;
            notFull.signal();
            return x;
        } finally {
            lock.unlock();
        }
    }
}
----

== Generic BlockingQueue using LinkedList

----
import java.util.LinkedList;
import java.util.Queue;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

public class BlockingQueue<T> {
    private Queue<T> queue = new LinkedList<T>();
    private int capacity;
    private Lock lock = new ReentrantLock();
    private Condition notFull = lock.newCondition();
    private Condition notEmpty = lock.newCondition();

    public BlockingQueue(int capacity) {
        this.capacity = capacity;
    }

    public void put(T element) throws InterruptedException {
        lock.lock();
        try {
            while (queue.size() == capacity) {
                notFull.await();
            }
            queue.add(element);
            notEmpty.signal();
        } finally {
            lock.unlock();
        }
    }

    public T take() throws InterruptedException {
        lock.lock();
        try {
            while (queue.isEmpty()) {
                notEmpty.await();
            }
            T item = queue.remove();
            notFull.signal();
            return item;
        } finally {
            lock.unlock();
        }
    }
}
----

Source: https://www.javacodemonk.com/blocking-queue-implementation-in-java-044ee033[Blocking Queue]

== LinkedBlockingQueue vs ConcurrentLinkedQueue

The LinkedBlockingQueue is an optionally-bounded blocking queue implementation, meaning that the queue size can be specified if needed.

Contain up to 100 elements:
----
BlockingQueue<Integer> boundedQueue = new LinkedBlockingQueue<>(100);
----
An unbounded LinkedBlockingQueue just by not specifying the size:
----
BlockingQueue<Integer> unboundedQueue = new LinkedBlockingQueue<>();
----
If there is no memory left, then the queue throws a java.lang.OutOfMemoryError. +
If the queue is full, then adding a new element will block the accessing thread unless there is space available for the new element. Similarly, if the queue is empty, then accessing an element blocks the calling thread.

=== ConcurrentLinkedQueue

A ConcurrentLinkedQueue is an unbounded, thread-safe, and non-blocking queue. +
It does not block a thread once the queue is empty. Instead, it returns null. +
Since its unbounded, it'll throw a java.lang.OutOfMemoryError if there's no extra memory to add new elements.
----
int element = 1;
ExecutorService executorService = Executors.newFixedThreadPool(2);
ConcurrentLinkedQueue<Integer> queue = new ConcurrentLinkedQueue<>();

Runnable offerTask = () -> queue.offer(element);

Callable<Integer> pollTask = () -> {
  while (queue.peek() != null) {
    return queue.poll().intValue();
  }
  return null;
};

executorService.submit(offerTask);
Future<Integer> returnedElement = executorService.submit(pollTask);
assertThat(returnedElement.get().intValue(), is(equalTo(element)));
----

|===
|Feature	|LinkedBlockingQueue	|ConcurrentLinkedQueue

|Blocking Nature
|It is a blocking queue and implements the BlockingQueue interface
|It is a non-blocking queue and does not implement the BlockingQueue interface

|Queue Size
|It is an optionally bounded queue, which means there are provisions to define the queue size during creation
|It is an unbounded queue, and there is no provision to specify the queue size during creation

|Locking Nature
|It is a lock-based queue
|It is a lock-free queue

|Algorithm
|It implements its locking based on two-lock queue algorithm
|It relies on the Michael & Scott algorithm for non-blocking, lock-free queues

|Implementation
|In the two-lock queue algorithm mechanism, LinkedBlockingQueue uses two different locks – the putLock and the takeLock. The put/take operations uses the first lock type, and the take/poll operations use the other lock type
|It uses CAS (Compare-And-Swap) for its operations

|Blocking Behavior
|It is a blocking queue. So, it blocks the accessing threads when the queue is empty
|It does not block the accessing thread when the queue is empty and returns null
|===



Source: https://www.baeldung.com/java-queue-linkedblocking-concurrentlinked[Linked vs Concurrent]
