= Synchronizers

== CyclicBarrier

CyclicBarrier in Java is a synchronizer introduced in JDK 5 on java.util.Concurrent

All threads which wait for each other to reach the barrier are called parties, CyclicBarrier is initialized with a number of parties to wait and threads wait for each other by calling CyclicBarrier.await() method which is a blocking method in Java and blocks until all Thread or parties call await().

await() is a blocking call but can be timed out or Interrupted by other threads.

If you look at CyclicBarrier it also does the same thing but it is different you can not reuse CountDownLatch once the count reaches zero while you can reuse CyclicBarrier by calling the reset() method which resets Barrier to its initial State.

What it implies that *CountDownLatch is good for one-time events* like application start-up time and CyclicBarrier can be used in case of the recurrent event like concurrently calculating a solution of the big problem etc.

Each thread calls await method in short duration but they don't proceed until all 3 threads reached the barrier, once all thread reaches the barrier, the barrier gets broker and each thread started their execution from that point.

https://github.com/eight9080/test/blob/master/src/main/java/com/example/concurent/CyclicBarrierExample.java[CyclicBarrierExample.java]

Output:
----
Output:
Thread 1 is waiting on the barrier
Thread 3 is waiting on the barrier
Thread 2 is waiting on the barrier
All parties have arrived at the barrier, lets play
Thread 3 has crossed the barrier
Thread 1 has crossed the barrier
Thread 2 has crossed the barrier
----

* CyclicBarrier can perform a completion task once all thread reaches to the barrier, This can be provided while creating CyclicBarrier.

* The thread will block on await() until all parties reach the barrier, another thread interrupts or await timed out

* If another thread interrupts the thread which is waiting on the barrier it will throw BrokernBarrierException

* CyclicBarrier.reset() put Barrier on its initial state, other thread which is waiting or not yet reached barrier will terminate with java.util.concurrent.BrokenBarrierException.

Read more: https://javarevisited.blogspot.com/2012/07/cyclicbarrier-example-java-5-concurrency-tutorial.html[Cyclic Barrier]


== CountDownLatch

CountDownLatch in Java is a kind of synchronizer which allows one Thread to wait for one or more Threads before starts processing.

* You can not reuse CountDownLatch once count is reaches zero, this is the main difference between CountDownLatch and CyclicBarrier

* Main Thread wait on Latch by calling *CountDownLatch.await()* method while other thread calls *CountDownLatch.countDown()* to inform that they have completed.

CountDownLatch works in latch principle, the main thread will wait until Gate is open. One thread waits for n number of threads specified while creating CountDownLatch in Java.

Any thread, usually the main thread of application, which calls CountDownLatch.await() will wait until count reaches zero or its interrupted by another Thread. All other threads are required to do a count down by calling CountDownLatch.countDown() once they are completed or ready to the job. as soon as count reaches zero, Thread awaiting starts running.

One of the disadvantages of CountDownLatch is that *it's not reusable* once count reaches zero you can not use CountDownLatch any more

https://github.com/eight9080/test/blob/master/src/main/java/com/example/concurent/CountDownLatchDemo.java[CountDownLatchDemo.java]

Output:
----
CacheService is Up
ValidationService is Up
AlertService is Up
All services are up, Application is starting now
----

Read more: https://javarevisited.blogspot.com/2012/07/countdownlatch-example-in-java.html[CountDownLatch]

== Explicit locking - Lock Pattern

=== ReentrantLock

* exclusion, read & wi=rite ordering

----
Lock lock = new ReentrantLock();
try{
    lock.lock();
}finally{
    lock.unlock();
}
----

* lockInterruptibly

* timed lock
----
Lock lock = new ReentrantLock();
if(lock.tryLock()){
    try{
        lock.lock();
    }finally{
        lock.unlock();
    }
}else{...}
----

If a thread is already executing the guarded block of code, then `tryLock` returns false immediately.

* Fair Lock Acquisition +
Default is not fair +
 Fairness means that the first to enter the wait line will also be the first to enter the guarded block of code.

==== Producer / Consumer Pattern: Lock Implementation with Condition

[source, java]
----
package test;

import java.util.concurrent.locks.ReentrantLock;
import java.util.concurrent.locks.Condition;

public class ProducerConsumer {

	private static Lock lock = new ReentrantLock();
	private static Condition notFull = lock.newCondition();
	private static Condition notEmpty = lock.newCondition();

	private static int[] buffer;
	private static int count;

	static class Producer {

		void produce() {
		    try {
		        lock.lock();
				while (isFull(buffer))
				    notFull.await();
				buffer[count++] = 1;
				notEmpty.signal();
            }finally{
                lock.unlock();
            }
		}
	}

	static class Consumer {

		void consume() {
			try {
			    lock.lock();
				while (isEmpty(buffer))
				    notEmpty.await();
                buffer[--count] = 0;
				notFull.signal();
			}finally{
			    lock.unlock();
			}
		}
	}

	static boolean isEmpty(int[] buffer) {
		return count == 0;
	}

	static boolean isFull(int[] buffer) {
		return count == buffer.length;
	}

	public static void main(String... strings) throws InterruptedException {

		buffer = new int[10];
		count = 0;

		Producer producer = new Producer();
		Consumer consumer = new Consumer();

		Runnable produceTask = () -> {
			for (int i = 0 ; i < 50 ; i++) {
				producer.produce();
			}
			System.out.println("Done producing");
		};
		Runnable consumeTask = () -> {
			for (int i = 0 ; i < 45 ; i++) {
				consumer.consume();
			}
			System.out.println("Done consuming");
		};

		Thread consumerThread = new Thread(consumeTask);
		Thread producerThread = new Thread(produceTask);

		consumerThread.start();
		producerThread.start();

		consumerThread.join();
		producerThread.join();

		System.out.println("Data in the buffer: " + count);
	}
}
----

* *Condition* - used to park and awake threads.

_The `await()` call is blocking, but can be interrupted_

* await()
* await(time, timeUnit)
* awaitNanos(nanosTimeout)
* awaitUntil(date)
* awaitUninterruptibly()

_A fair Lock generates fair Condition._

=== ReadWriteLock

* readLock()
* writeLock()

* Only one thread can hold the write lock
* When the write lock is held -> no one can hold the read lock
* As many threads as needed can hold the read lock

Cache thread safe implementation

[source, java]
----
package test;

import java.util.concurrent.locks.ReentrantLock;
import java.util.concurrent.locks.Condition;

public class Example {

    public static void main(String[] args){

     ReadWriteLock lock = new ReentrantReadWriteLock();

     Lock readLock = lock.readLock();
     Lock writeLock = lock.writeLock();

     Map<long, String> cache = new HashMap<>();

     try{
      readLock.lock();
      return cache.get(key);
     }finally{
      readLock.unlock();
     }

     try{
      writeLock.lock();
      cache.put(key, value);
     }finally{
      writeLock.unlock();
     }
    }
}
----

=== Semaphore Pattern

* allows several threads in the same block of code
* aquire method is blocking until a permit is available

----
Semaphore semaphore = new Semaphore(5); //permits

try{
 semaphore.acquire();
///
}finally{
 semaphore.release();
}
----

=== Barrier

* to have several tasks wait for each other

Finding prime numbers from a set of numbers

----
CyclicBarrier barrier = new CyclicBarrier(4);
----

[source,java]
----
import  java.util.concurrent.CyclicBarrier;

public class Worker implements Callable<List<Integer>> {
    private CyclicBarrier barrier;
    private List<Integer> inputList;

    public Worker(CyclicBarrier barrier, List<Integer> inputList){
        this.barrier = barrier;
        this.inputList = inputList;
    }

    public List<Integer> call() {
        List<Integer> result = findPrimes(inputSet);
        try{
         barrier.await(); //Blocks until everybody is ready
        }catch(InterruptedException | BrokenBarrierException e){}
        return result;
    }
}
----

Main thread
----
CyclicBarrier barrier = new CyclicBarrier(4);
ExecutorService service = Executors.newFixedThreadPool(4);

Worker worker1 = new Worker(barrier, inputList1);
//more workers

Future<List<Integer>> future1 = executors.submit(worker1);
//more submissions

List<Integer> finalList = new ArrayList(future1.get());
finalList.addAll(future2.get()):
// more results
----

The `await()` call is *blocking*

* await()
* await(time, timeUnit)

Once opened a barrier is normally reset.

The reset() methods resets the barrier exceptionally, causing the waiting tasks to throw a BrokenBarrierException.

CyclicBarrier

* a tool to synchronize several threads between them, and let them continue when they reach a common point.

* the barrie closes again once opened, allowing for cyclic computations, can also be reset.

=== Latch

* to count down operations and let a task start

*CountDownLatch*

[source, java]
----
public class ServiceWorker implements Callable<String> {
    private CountDownLatch latch;
    private Service service;

    public ServiceWorker(CounDownLatch latch, Service service){
        this.latch = latch;
        this.service = service;
    }

    public Boolean call(){
        service.init();
        latch.countDown();
        return true;
    }
}
----

Main thread

----
CountDownLatch latch = new CountDownLatch(3);
ExecutorService service = Executors.newFixedThreadPool(4);

ServiceWorker worker1 = new ServiceWorker(latch, dataService);
//more workers

Future<Boolean> future1 = executors.submit(worker1);
//more submissions

try{
 latch.await(10, TimeUnit.SECONDS); //blocks until the count reaches 0
 server.start();
} cathc (InterrupedException e){
 //errors
}
----

The CountDownLatch cannot be closed again ->  good tool to control the firing up of an application.

=== Phaser

* to build logic in which threads need to wait on the barrier before going to the next step of execution.
* Each phase can have a different number of threads waiting for advancing to another phase.
* the thread needs to register() itself with the Phaser instance.
* The thread signals that it arrived at the barrier by calling the arriveAndAwaitAdvance(), which is a blocking method.
* When the number of arrived parties is equal to the number of registered parties, the execution of the program will continue, and the phase number will increase.
* When the thread finishes its job, we should call the arriveAndDeregister() method to signal that the current thread should no longer be accounted for in this particular phase.

[source, java]
----
class LongRunningAction implements Runnable {
    private String threadName;
    private Phaser ph;

    LongRunningAction(String threadName, Phaser ph) {
        this.threadName = threadName;
        this.ph = ph;
        ph.register();
    }

    @Override
    public void run() {
        ph.arriveAndAwaitAdvance();
        try {
            Thread.sleep(20);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        ph.arriveAndDeregister();
    }
}
----

Initialize phaser
----
ExecutorService executorService = Executors.newCachedThreadPool();
Phaser ph = new Phaser(1);

assertEquals(0, ph.getPhase());
----

three LongRunningAction action threads, which will be waiting on the barrier until we will call the arriveAndAwaitAdvance() method from the main thread.
----
executorService.submit(new LongRunningAction("thread-1", ph));
executorService.submit(new LongRunningAction("thread-2", ph));
executorService.submit(new LongRunningAction("thread-3", ph));

ph.arriveAndAwaitAdvance();

assertEquals(1, ph.getPhase());
----

two threads should conduct the next phase of processing
----
executorService.submit(new LongRunningAction("thread-4", ph));
executorService.submit(new LongRunningAction("thread-5", ph));
ph.arriveAndAwaitAdvance();

assertEquals(2, ph.getPhase());

ph.arriveAndDeregister();
----

Output
----
This is phase 0
This is phase 0
This is phase 0
Thread thread-2 before long running action
Thread thread-1 before long running action
Thread thread-3 before long running action
This is phase 1
This is phase 1
Thread thread-4 before long running action
Thread thread-5 before long running action
----

Source: https://www.baeldung.com/java-phaser[Java Phaser]


== CASing and Atomic Variables

*Compare and Swap*

* If the current value at that address in memory is the expected value, then it is replaced by the new value and returns true.
* If not, it returns false

-> atomic assembly instructions


=== AtomicLong
* safe incrementation of a counter without synchronization

----
AtomicLong counter = new AtomicLong(10L);
long newValue = counter.incrementAndGet();
----

Under the hood:

* the API tries to apply the incrementation
* the CASing tells the calling code if the incrementation failed
* if it did, the API tries again

=== AtomicBoolean

* get() and set()
* getAndSet(value) -> return the current value and update this value to the past value
* compareAndSet(expected, value) -> the CASing method with an expected value and the new value to be set if the expected value is matched

=== AtomicInteger and AtomicLong

* get() and set()
* getAndSet(value)
* compareAndSet(expected, value)
* getAndUpdate(unaryOp) updateAndGet(unaryOp) -> unaryOp lamda exp
* getAndIncrement(), getAndDecrement()
* getAndAdd(value), addAndGet(value) -> will increment the current value with the past value
* getAndAccumulate(value, binOp) and accumulateAndGet(value, binOp) -> This binary operator will operate and the current value at that location and the past value as a parameter to compute the new value to be set

=== AtomicReference(V)

A wrapper on the reference that is on a pointer

* get() and set()
* getAndSet(value)
* compareAndSet(expected, value)
* getAndUpdate(unaryOp) updateAndGet(unaryOp)
* getAndAccumulate(value, binOp) and accumulateAndGet(value, binOp)

== Adders and Accumulators

The LongAdder can be seen as an AtomicLong that does not expose the get functionality at each modification and that can optimize things.

* it does not return the updated value
* it can distribute the update on different cells
* it can merge the results on a get call

=== Long Adder

* increment(), decrement()
* add(long)
* sum(), longValue(), intValue() -> return the content of this long adder
* sumThenReset() -> return the content of the adder and reset to 0

=== LongAccumulator

* built on a binary operator
* accumulate(long) -> The current value and this past value will be used as parameters of this binary operator to produce a new value
* get() -> return the value computed in this accumulator
* getThenReset()
* intValue(), longValue(), floatValue(), doubleValue()
















