= Architecture Requirements Management

* Ensure that the Requirements Management process is sustained and operates for all relevant ADM phases
* Manage architecture requirements identified during any execution of the ADM cycle or a phase
* Ensure that relevant architecture requirements are available for use by each phase as the phase is executed

== Inputs

Inputs to the Requirements Management phase are:

* A populated Architecture Repository 
* Organizational Model for Enterprise Architecture including:
    ** Scope of organizations impacted
    ** Maturity assessment, gaps, and resolution approach
    ** Roles and responsibilities for architecture team(s)
    ** Constraints on architecture work
    ** Budget requirements
    ** Governance and support strategy

* Tailored Architecture Framework including:
    ** Tailored architecture method
    ** Tailored architecture content (deliverables and artifacts)
    ** Configured and deployed tools
* Statement of Architecture Work
* Architecture Vision
* Architecture requirements, populating an Architecture Requirements Specification
* Requirements Impact Assessment

== Outputs

* Requirements Impact Assessment
* Updated Architecture Requirements Specification

== Approach

NOTE: the Requirements Management circle denotes not a static set of requirements, but a dynamic process whereby requirements for Enterprise Architecture and subsequent changes to those requirements are identified, stored, and fed into and out of the relevant ADM phases, and also between cycles of the ADM.


=== Requirements Development

* The first *high-level requirements* are articulated as part of the *Architecture Vision*, generated by means of the business scenario or analogous technique.


At the completion of the phase the status of all such requirements needs to be updated.

During the phase execution, new requirements generated for future architecture work within the scope of the current Statement of Architecture Work need to be documented within the Architecture Requirements Specification, and new requirements which are *outside* of the scope of the current Statement of Architecture Work must be input to the Architecture Requirements Repository for management through the Requirements Management process.

Types of requirement:

* Functional requirements
* Non-functional requirements

IMPORTANT: The business scenarios technique is an appropriate and effective technique to discover and document business requirements.




