= Architecture contracts

IMPORTANT: Joint agreements between development partners and sponsors on the deliverables, quality, and fitness-for-purpose of an architecture

By implementing a governed approach to the management of contracts:

* A system of continuous monitoring to check integrity, changes, decision-making, and audit of all architecture-related activities within the organization

* Adherence to the principles, standards, and requirements of the existing or developing architectures

* Identification of risks in all aspects of the development and implementation of the architecture(s) covering the internal development against accepted standards, policies, technologies, and products as well as the operational aspects of the architectures such that the organization can continue its business within a resilient environment

* A set of processes and practices that ensure accountability, responsibility, and discipline with regard to the development and usage of all architectural artifacts

* A formal understanding of the governance organization responsible for the contract, their level of authority, and scope of the architecture under the governance of this body



