= Establishing an Architecture Capability

== Phase A: Architecture Vision

* *Establish the Project* -> this step should focus on defining the stakeholders in the architecture practice

* *Identify Stakeholders and Concerns, Business Requirements, and Architecture Vision* -> this step generates the first, very high-level definitions of the baseline and target environments, from a business information systems and technology perspective for the architecture practice

* Identify Business Goals and Business Drivers

* Define scope

* Define Constraints

* Review Architecture Principles, including Business Principles

* Develop Statement of Architecture Work and Secure Approval

== Phase B: Business Architecture

* *Architecture Ontology* -> defining the architectural terms and definitions that will be used in the organization in order to establish a common understanding of these terms

* *Architecture Process* -> where the ADM would form the base of the process and need to be customized to meet the organization’s requirements and architecture practice vision

* *Architecture Viewpoints and Views* that list all the viewpoints and views that should be addressed by the architecture practice

* *Architecture Framework* -> describing the various architecture deliverables that will be generated by the architecture practice, the inter-relationships and dependencies between the architecture deliverables, as well as the rules and guidelines governing the design of these deliverables

* *Architecture Accountability Matrix* -> defining the roles in the architecture practice and allocating accountability of the roles to architecture deliverables and processes

* *Architecture Performance Metrics* -> identifying and describing the metrics that will be used to monitor the performance of the architecture practice against its stated architecture practice vision and objectives

* *Architecture Governance Framework* which is a specific view of the defined architecture process and Architecture Accountability Matrix

== Phase C: Data Architecture

* specify and govern the structure of the organization’s Enterprise Continuum and Architecture Repository

== Phase C: Application Architecture

* defines the functionality required to generate, maintain, publish, distribute, and govern the architecture deliverables as defined in the architecture framework.

== Phase D: Technology Architecture

* define technology infrastructure supporting the architecture practice.

== Phase E: Opportunities & Solutions

* A critical factor to consider during this phase of planning the establishment of the architecture practice is the organizational change that is required and how this will be achieved.

== Phase F: Migration Planning

The adoption of the architecture process and framework will have a major impact on the overall establishment of the architecture practice in the organization.

== Phase G: Implementation Governance

Changing practices within the organization to adopt a more structured and disciplined approach will be a challenge and should be addressed by the appropriate organizational change techniques.

== Phase H: Architecture Change Management

A typical change would be the requirement for a new architecture deliverable. This would impact on all the architecture domains of the architecture practice.

== Requirements Management
Requirements should be clearly articulated and align to the architecture practice vision.





