= NIO

== NIO – java.nio
The java.nio package was introduced in Java 1.4 and updated in Java 1.7 (NIO.2) with enhanced file operations and an ASynchronousSocketChannel.

NIO - non-blocking IO

* It deals with buffers and channels
* It supports asynchronous operations
* NIO may be more efficient than I/O

=== Java NIO API

Java I/O

-  writes one byte/char at a time
- buffering occurs in the JVM heap memory
- all operations are synchronous

NIO provides:

- bulk access to raw bytes
- bidirectional channels - a single Java object, you can both read and write data to and from the disc or to and from the network
- off-heap buffering
- proper support for charsets
- support for asynchronous operations

New concepts:

- Buffer - where the data resides +
A space in memory -> resides in the main memory of the JVM, the heap or off-heap
- Channel - where the data comes from +
An object that connects to a file or to a circuit +
Writes the buffer to a medium or can read data from that medium to a buffer. +
A channel only knows bytes buffers so it can only read and write bytes from files or for circuits
- Selector - for asynchronous operations

_A write operation takes data from a buffer and writes it to a channel._

_A read operation takes data from a channel and writes it into a buffer._

==== Channels

*FileChannel*

- access a file
- it has a cursor
- multiple reads and writes
- thread safe

In-memory File Channels:

- can be mapped to a memory array for direct access
- built on OS features for fast access
- a single write in this array can trigger a modification of the file on the disk

Modes for the mapping:

- READ_ONLY - the mapped file cannot be modified
- READ_WRITE - can read/write
- PRIVATE - modifications are local to this channel and will not be propagated to the disk

*DatagramChannel*

- access a socket
- it supports multicast
- supports multiple non-concurrent reads and writes


*SochetChannel* and *ServerSocketChannel*

- access a TCP socket
- supports asynchronous operations
- supports multiple non-concurrent reads and writes


===== Buffers

An in-memory structure
An array

- ByteBuffer
- CharBuffer
- IntBuffer

Properties:

- capacity - size of the backing array
- current position
- limit

Operations:

- rewind - clears the mark and sets the current position to 0
- reset - sets the current position to the previously set mark
- flip - sets the limit to the current position and rewinds the buffer
- clear - clears the buffer

==== Write content to a file

----
ByteBuffer buffer = ByteBuffer.allocate(1024);
buffer.putInt(10);
FileChannel fileChannel = FileChannel.open(Paths.get("files/ints.bin"), CREATE, WRITE);
buffer.flip();
fileChannel.write(byteBuffer);
fileChannel.close();
----

==== Read content from a file

----
FileChannel fileChannel = FileChannel.open(Paths.get("files/int.bin"), READ);
ByteBuffer byteBuffer = ByteBuffer.allocate(1024);
fileChannel.read(byteBuffer);
byteBuffer.flip();
IntBuffer intBuffer = byteBuffer.asIntBuffer();
int i = intBuffer.get();
----

==== Reading and writing to multiple Buffers

===== Scattering Read Operation

The Scattering read consists in reading from a single channel to an array of buffers.

*ScatteringByteChannel* interface

The reading process fills the first buffer before moving to the next one

----
FileChannel fileChannel = FileChannel.open(Paths.get("files/int.bin"), READ);
ByteBuffer header = ByteBuffer.allocate(1024);
ByteBuffer body = ByteBuffer.allocate(4096);
ByteBuffer footer = ByteBuffer.allocate(128);
ByteBuffer[] message = {header, body, footer};

long bytesRead = fileChannel.read(message);
----


====== Gathering Write Operation

The Gathering Write consists in writing from an array of buffers to a single Channel.

*ScatteringByteChannel* interface

The writing operation starts with the first buffer, then the next one and so on.

* recommended with messages of fixed-length parts

----
ByteBuffer header = ByteBuffer.allocate(1024);
ByteBuffer body = ByteBuffer.allocate(4096);
ByteBuffer footer = ByteBuffer.allocate(128);

header.putInt(10);
headbodyer.putInt(10);
footer.putInt(10);

ByteBuffer[] message = {header, body, footer};

FileChannel fileChannel = FileChannel.open(Paths.get("files/ints.bin"), CREATE, WRITE);
long bytesWritten = fileChannel.write(message);
fileChannel.close();
----

==== MappedByteBuffer

* Buffer maps a file to memory +
* Recommend for apps that read the same file many times. +
* Can be used for a portion of a file +
* Modes: READ, READ_WRITE, PRIVATE

----
FileChannel fileChannel = FileChannel.open(Paths.get("files/int.bin"), READ);
MappedByteBuffer mappedBuffer = fileChannel.map(FileChannel.MapMode.READ_ONLY, 0, fileChannel.size());
CharBuffer charBuffer = StandardsCharsets.UTF_8.decode(mappedBuffer);
----

==== Charsets

* US_ASCII, ISO_8859_1
* UTF_8

`encode()` takes a CharBuffer returns ByteBuffer

`decode()` takes a ByteBuffer returns a Charbuffer

----
FileChannel channel = FileChannel.open(paths.get("file.txt"), StandardOpenOperation.READ);
ByteBuffer buffer = ByteBuffer.allocate(1024);
channel.read(buffer);

CharSet latin1 = StandardsCharsets.ISO_8859_1;
CharBuffer utf8Buffer = latin1.decode(buffer);
String result = new String(utf8buffer.array());

CharSet utf8 = StandardsCharsets.UTF_8;
ByteBuffer byteBuffer = utf8.encode(buffer);
fileChannel.write(byteBuffer);
----

=== Asynchronous operations with NIO

With synchronous read, each read operation is conducted in its own thread. +
With asynchronous reads, a single thread can handle many read operations.

==== Selectors

Events for file channels :

* READ, WRITE - channel is ready for reading/writing

Events Socket channels:

* CONNECT - a connection was established
* ACCEPT - a connection was accepted

The registration is configured to listen to certain events.

*Aync Network Reader*

----
ServerSocketChannel serverSocketChannel = ServerSocketChannel.open();
serverSocketChannel.configureBlocking(false);

ServerSocket serverSocket = serverSocketChannel.socket();
serverSocket.bind(new InetSocketAddress(12345));

Selector selector = Selector.open();
SelectionKey key = channel.register(selector, SelectionKey.OP_ACCEPT); //registers selector with the ACCEPT event
// Selection key - can be stored to unregister, check for validity.

int n = selector.select(); // server socket channel is listening to incomming requests
// the select() call is blocking until events are available
// n is the number of keys with available events.

Set<Selectionkey> keys = selector.selectedKeys(); // the keys that got events are returned in a set
for(SelectionKey key : keys) {
    // stuff with the corresponding channel
    if((key.readyOps() & SelectionKey.OP_ACCEPT) == SelectionKey.OP_ACCEPT) { //check if a connection request
        ServerSocketChannel channel = (ServerSocketChannel)key.channel();

        SocketChannel socketChannel = channel.accept();
        socketChannel.configureBlocking(false);
        socketChanenl.register(selector, SelectionKey.OP_READ);
    }
    else if((key.readyOps() & SelectionKey.OP_READ) == SelectionKey.OP_READ) ){
        SocketChannel channel = (SocketChannel)key.channel();
        channel.accept(byteBuffer); //read data in a buffer

        //clean up
        byteBuffer.clear();
        selectedKeys.remove(key);
        key.cancel();
        channel.close();
    }
}

----

=== Java NIO 2 - FileSystems









=== Setup NIO

It provides:

* *Buffer* – to read chunks of data at a time
* *CharsetDecoder* – for mapping raw bytes to/from readable characters
* *Channel* – for communicating with the outside world
* *Selector* – to enable multiplexing on a SelectableChannel and provide access to any Channels that are ready for I/O
non-blocking mode – to read whatever is ready

=== Configure Our Test Server
----
<dependency>
    <groupId>com.github.tomakehurst</groupId>
    <artifactId>wiremock-jre8</artifactId>
    <version>2.26.3</version>
    <scope>test</scope>
</dependency>
----

----
@Rule public WireMockRule wireMockRule = new WireMockRule(wireMockConfig().dynamicPort());

private String REQUESTED_RESOURCE = "/test.json";

@Before
public void setup() {
    stubFor(get(urlEqualTo(REQUESTED_RESOURCE))
      .willReturn(aResponse()
      .withStatus(200)
      .withBody("{ \"response\" : \"It worked!\" }")));
}
----

=== Send a Request
create a java.nio.channel.SocketChannel to access the port on our server, and pass it an InetSocketAddress

----
InetSocketAddress address = new InetSocketAddress("localhost", wireMockRule.port());
SocketChannel socketChannel = SocketChannel.open(address);
----
With a standard UTF-8 Charset to encode and write our message:
----
Charset charset = StandardCharsets.UTF_8;
socket.write(charset.encode(CharBuffer.wrap("GET " + REQUESTED_RESOURCE + " HTTP/1.0\r\n\r\n")));
----

=== Read the Response
a ByteBuffer for the raw bytes and a CharBuffer for the converted characters
----
ByteBuffer byteBuffer = ByteBuffer.allocate(8192);
CharsetDecoder charsetDecoder = charset.newDecoder();
CharBuffer charBuffer = CharBuffer.allocate(8192);
----

Fast performance -> create a MappedByteBuffer in native memory using ByteBuffer.allocateDirect(). +
Using allocate() from the standard heap is fast enough. - for this case

When dealing with buffers, we need to know how big the buffer is (the capacity), where we are in the buffer (the current position), and how far we can go (the limit).

Let's read from our SocketChannel, passing it our ByteBuffer to store our data. Our read from the SocketChannel will finish with our ByteBuffer‘s current position set to the next byte to write to (just after the last byte written), but with its limit unchanged:
----
socketChannel.read(byteBuffer)
----
Our SocketChannel.read() returns the number of bytes read that could be written into our buffer. This will be -1 if the socket was disconnected.

When our buffer doesn't have any space left because we haven't processed all its data yet, then SocketChannel.read() will return zero bytes read but our buffer.position() will still be greater than zero.

use Buffer.flip() to set our ByteBuffer‘s current position to zero and its limit to the last byte that was written by the SocketChannel. We'll then save the buffer contents using our storeBufferContents method, which we'll look at later. Lastly, we'll use buffer.compact() to compact the buffer and set the current position ready for our next read from the SocketChannel.

----
while (socketChannel.read(byteBuffer) != -1 || byteBuffer.position() > 0) {
    byteBuffer.flip();
    storeBufferContents(byteBuffer, charBuffer, charsetDecoder, ourStore);
    byteBuffer.compact();
}
----
And let's not forget to close() our socket (unless we opened it in a try-with-resources block):
----
socketChannel.close();
----

=== Storing Data From Our Buffer

* decode the raw bytes into characters in our CharBuffer
* flip the pointers so that we can read our character data, and append it to our expandable StringBuilder.
* clear the CharBuffer ready for the next write/read cycle.

----
void storeBufferContents(ByteBuffer byteBuffer, CharBuffer charBuffer,
  CharsetDecoder charsetDecoder, StringBuilder ourStore) {
    charsetDecoder.decode(byteBuffer, charBuffer, true);
    charBuffer.flip();
    ourStore.append(charBuffer);
    charBuffer.clear();
}
----







== Http download using Java NIO FileChannel
Java’s Channel should always be preferred for IO related stuff because Channel can utilize OS specific optimization while dealing with the files. An input stream can easily be converted to a FileChannel using Channels.newChannel() static factory method.

[source, java]
----
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URI;
import java.nio.channels.Channels;
import java.nio.channels.FileChannel;
import java.nio.channels.ReadableByteChannel;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.EnumSet;

public class HttpDownloader {

    public File download(URI uri, String fileName) throws IOException {
        Path path = Paths.get(fileName);
        long totalBytesRead = 0L;
        HttpURLConnection con = (HttpURLConnection) uri.resolve(fileName).toURL().openConnection();
        con.setReadTimeout(10000);
        con.setConnectTimeout(10000);
        try (ReadableByteChannel rbc = Channels.newChannel(con.getInputStream());
             FileChannel fileChannel = FileChannel.open(path, EnumSet.of(StandardOpenOption.CREATE, StandardOpenOption.WRITE));) {
            totalBytesRead = fileChannel.transferFrom(rbc, 0, 1 << 22); // download file with max size 4MB
            System.out.println("totalBytesRead = " + totalBytesRead);
            fileChannel.close();
            rbc.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return path.toFile();
    }
}
----

Source: https://www.javacodemonk.com/http-download-using-java-nio-filechannel-f6196fc4[download]

== CRC32 checksum calculation Java NIO
Few of the times we wish the speed of C and syntax of Java for doing some IO intensive task in Java. Calculation of CRC is one of them task which requires a efficient implementation in order to give good performance.

----
public static long calculateCRC(File filename) {
     final int SIZE = 16 * 1024;
     try (FileInputStream in = new FileInputStream(filename);) {
         FileChannel channel = in.getChannel();
         CRC32 crc = new CRC32();
         int length = (int) channel.size();
         MappedByteBuffer mb = channel.map(FileChannel.MapMode.READ_ONLY, 0, length);
         byte[] bytes = new byte[SIZE];
         int nGet;
         while (mb.hasRemaining()) {
             nGet = Math.min(mb.remaining(), SIZE);
             mb.get(bytes, 0, nGet);
             crc.update(bytes, 0, nGet);
         }
         return crc.getValue();
     } catch (FileNotFoundException e) {
         e.printStackTrace();
     } catch (IOException e) {
         e.printStackTrace();
     }
     throw new RuntimeException("unknown IO error occurred ");
 }
----



Source: https://www.javacodemonk.com/crc32-checksum-calculation-java-nio-c26893db[checksum]