= Business Transformation Readiness Assessment

The recommended activities in an assessment of an organization’s readiness to address business transformation are:

* Determine the readiness factors that will impact the organization
* Present the readiness factors using maturity models
* Assess the readiness factors, including determination of readiness factor ratings
* Assess the risks for each readiness factor and identify improvement actions to mitigate the risk
* Work these actions into Phase E and F Implementation and Migration Plan

== Determine Readiness Factors

* *Vision* is the ability to clearly define and communicate what is to be achieved
This is where management is able to clearly define the objectives, in both strategic and specific terms.

* *Desire, Willingness, and Resolve* is the presence of a desire to achieve the results, willingness to accept the impact of doing the work, and the resolve to follow through and complete the endeavor

* *Need*, in that there is a compelling need to execute the endeavor

* *Business Case* exists that creates a strong focus for the project, identifying benefits that must be achieved and thereby creating an imperative to succeed

* *Funding*, in the form of a clear source of fiscal resources, exists that meets the endeavor’s potential expenditures

* *Sponsorship and Leadership* exists and is broadly shared, but not so broad as to diffuse accountability

* *Governance* is the ability to engage the involvement and support of all parties with an interest in or responsibility to the endeavor with the objective of ensuring that the corporate interests are served and the objectives achieved

* *Accountability* is the assignment of specific and appropriate responsibility, recognition of measurable expectations by all concerned parties, and alignment of decision-making with areas of responsibility and with where the impact of the decisions will be felt

* *Workable Approach and Execution Model* is an approach that makes sense relative to the task, with a supporting environment, modeled after a proven approach

* *IT Capacity to Execute* is the ability to perform all the IT tasks required by the project, including the skills, tools, processes, and management capability

* *Enterprise Capacity to Execute* is the ability of the enterprise to perform all the tasks required by the endeavor, in areas outside of IT, including the ability to make decisions within the tight time constraints typical to project environments based upon the recent successful execution of a similar endeavor of at least half the size and complexity

* *Enterprise Ability to Implement and Operate* the transformation elements and their related business processes, absorb the changes arising from implementation, and ongoing ability to operate in the new environment








